### ISSUE TITLE
Unificação de tabela

### ISSUE THREAD

**Issue by douglasliberty** [rictom/cnpj-sqlite#1]
Olá, Existe a possibilidade de unir a tabela "SIMPLES" com a informação do OPC MEI na tabela "ESTABELECIMENTOS"? pois preciso das informações que existem na aba "ESTABELECIMENTO" com filtro do OPC_MEI em "S"

**Comment by rictom** [comment]
Para juntar as duas tabelas, vc abre o cnpj.db em um programa como o DB Browser for SQLite e roda uma sql como 
create table estabelecimento_simples as
select *
from estabelecimento te
left join simples ts on ts.cnpj_basico=te.cnpj_basico

Isso irá criar uma tabela estabelecimento_simples (imagino que isso possa demorar). Dependendo do que vc está fazendo, deve ser melhor por um where limitando a sua consulta, ou criar algum índice.
