### ISSUE TITLE
Produtores Rurais

### ISSUE THREAD

**Issue by outboundleadsandsales** [rictom/cnpj-sqlite#10]
Prezados, peço uma ajuda;

por favor, como posso retornar os dados de Natureza Jurídica "4120 - produtor rural"?

preciso ter uma base completa com dados (nome, endereço, telefone, etc) de Produtores Rurais; por favor, podem me ajudar qual o script para uso no DB Browser?

**Comment by rictom** [comment]
A coluna natureza_juridica está na tabela empresas, então coloque na clausula where
natureza_juridica='4120'
