### ISSUE TITLE
Meses anteriores

### ISSUE THREAD

**Issue by lucasjome** [rictom/cnpj-sqlite#11]
Opa, já agradeço por disponibilizar os dados abertos de CNPJ em SQLITE atualizados.

Gostaria de saber se você teria como disponibilizar os arquivos dos últimos 12 meses?
Ou melhor, arquivos de 07/2021, 01/2022 e 07/2022?

**Comment by rictom** [comment]
Olá @lucasjome,
Vou tentar colocar os arquivos desses três meses em algum site de compartilhamento, depois te repasso o link. Você pode dar uma idéia geral do seu projeto?

**Comment by lucasjome** [comment]
Opa, muito obrigado.

Estou estudando a variação de CNPJs ativos e inativos, a nível semestral. 

Fico no aguardo dos arquivos então.

**Comment by rictom** [comment]
Carreguei os três meses em https://mega.nz/folder/XuhnlCpB#S51VwizfEdmWdsPCvcgerw . O de julho/2021 foi dividido em pedaços... Baixe tudo localmente e abre usando o 7zip. Me avise quando baixar e estiver tudo ok, que talvez eu precise apagar para liberar espaço.
