### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by Eduardomb22** [rictom/cnpj-sqlite#13]
Prezado, não sou técnico e gostaria, se possível, de uma ajuda

Quando executo o script, apresenta este erro:
Sun Jan 29 21:13:17 2023 descompactando dados-publicos-zip\Socios9.zip
carregando tabela dados-publicos\F.K03200$Z.D30114.CNAECSV
Traceback (most recent call last):
  File "K:\Nova pasta\dados_cnpj_para_sqlite.py", line 50, in <module>
    carregaTabelaCodigo('.CNAECSV','cnae')
  File "K:\Nova pasta\dados_cnpj_para_sqlite.py", line 48, in carregaTabelaCodigo
    engine.execute(f'CREATE INDEX idx_{nomeTabela} ON {nomeTabela}(codigo);')
    ^^^^^^^^^^^^^^
AttributeError: 'Engine' object has no attribute 'execute'

O que pode ser?

**Comment by rictom** [comment]
Olá @Eduardomb22 ,

Se vc copiar todo o texto do console, incluindo o comando que vc deu para executar o script, facilitaria a debugar o problema.

Talvez seja uma algo semelhante a isto, na hora de usar a rotina para mysql: https://github.com/rictom/cnpj-mysql/issues/3

**Comment by Eduardomb22** [comment]
> :\cnpj>python dados_cnpj_para_sqlite.py
> Início: Mon Jan 30 18:10:48 2023
> Mon Jan 30 18:10:48 2023 descompactando K:\cnpj\dados-publicos-zip\Cnaes.zip
> Mon Jan 30 18:10:48 2023 descompactando K:\cnpj\dados-publicos-zip\Empresas0.zip
> Mon Jan 30 18:10:52 2023 descompactando K:\cnpj\dados-publicos-zip\Empresas1.zip
> Mon Jan 30 18:10:53 2023 descompactando K:\cnpj\dados-publicos-zip\Empresas2.zip
> Mon Jan 30 18:10:54 2023 descompactando K:\cnpj\dados-publicos-zip\Empresas3.zip
> Mon Jan 30 18:10:56 2023 descompactando K:\cnpj\dados-publicos-zip\Empresas4.zip
> Mon Jan 30 18:10:58 2023 descompactando K:\cnpj\dados-publicos-zip\Empresas5.zip
> Mon Jan 30 18:10:59 2023 descompactando K:\cnpj\dados-publicos-zip\Empresas6.zip
> Mon Jan 30 18:11:01 2023 descompactando K:\cnpj\dados-publicos-zip\Empresas7.zip
> Mon Jan 30 18:11:02 2023 descompactando K:\cnpj\dados-publicos-zip\Empresas8.zip
> Mon Jan 30 18:11:04 2023 descompactando K:\cnpj\dados-publicos-zip\Empresas9.zip
> Mon Jan 30 18:11:05 2023 descompactando K:\cnpj\dados-publicos-zip\Estabelecimentos0.zip
> Mon Jan 30 18:11:19 2023 descompactando K:\cnpj\dados-publicos-zip\Estabelecimentos1.zip
> Mon Jan 30 18:11:24 2023 descompactando K:\cnpj\dados-publicos-zip\Estabelecimentos2.zip
> Mon Jan 30 18:11:30 2023 descompactando K:\cnpj\dados-publicos-zip\Estabelecimentos3.zip
> Mon Jan 30 18:11:35 2023 descompactando K:\cnpj\dados-publicos-zip\Estabelecimentos4.zip
> Mon Jan 30 18:11:40 2023 descompactando K:\cnpj\dados-publicos-zip\Estabelecimentos5.zip
> Mon Jan 30 18:11:45 2023 descompactando K:\cnpj\dados-publicos-zip\Estabelecimentos6.zip
> Mon Jan 30 18:11:50 2023 descompactando K:\cnpj\dados-publicos-zip\Estabelecimentos7.zip
> Mon Jan 30 18:11:55 2023 descompactando K:\cnpj\dados-publicos-zip\Estabelecimentos8.zip
> Mon Jan 30 18:12:00 2023 descompactando K:\cnpj\dados-publicos-zip\Estabelecimentos9.zip
> Mon Jan 30 18:12:05 2023 descompactando K:\cnpj\dados-publicos-zip\Motivos.zip
> Mon Jan 30 18:12:05 2023 descompactando K:\cnpj\dados-publicos-zip\Municipios.zip
> Mon Jan 30 18:12:05 2023 descompactando K:\cnpj\dados-publicos-zip\Naturezas.zip
> Mon Jan 30 18:12:05 2023 descompactando K:\cnpj\dados-publicos-zip\Paises.zip
> Mon Jan 30 18:12:05 2023 descompactando K:\cnpj\dados-publicos-zip\Qualificacoes.zip
> Mon Jan 30 18:12:05 2023 descompactando K:\cnpj\dados-publicos-zip\Simples.zip
> Mon Jan 30 18:12:11 2023 descompactando K:\cnpj\dados-publicos-zip\Socios0.zip
> Mon Jan 30 18:12:13 2023 descompactando K:\cnpj\dados-publicos-zip\Socios1.zip
> Mon Jan 30 18:12:14 2023 descompactando K:\cnpj\dados-publicos-zip\Socios2.zip
> Mon Jan 30 18:12:15 2023 descompactando K:\cnpj\dados-publicos-zip\Socios3.zip
> Mon Jan 30 18:12:16 2023 descompactando K:\cnpj\dados-publicos-zip\Socios4.zip
> Mon Jan 30 18:12:16 2023 descompactando K:\cnpj\dados-publicos-zip\Socios5.zip
> Mon Jan 30 18:12:17 2023 descompactando K:\cnpj\dados-publicos-zip\Socios6.zip
> Mon Jan 30 18:12:18 2023 descompactando K:\cnpj\dados-publicos-zip\Socios7.zip
> Mon Jan 30 18:12:19 2023 descompactando K:\cnpj\dados-publicos-zip\Socios8.zip
> Mon Jan 30 18:12:20 2023 descompactando K:\cnpj\dados-publicos-zip\Socios9.zip
> carregando tabela K:\cnpj\dados-publicos\F.K03200$Z.D30114.CNAECSV
> Traceback (most recent call last):
>   File "K:\cnpj\dados_cnpj_para_sqlite.py", line 50, in <module>
>     carregaTabelaCodigo('.CNAECSV','cnae')
>   File "K:\cnpj\dados_cnpj_para_sqlite.py", line 48, in carregaTabelaCodigo
>     engine.execute(f'CREATE INDEX idx_{nomeTabela} ON {nomeTabela}(codigo);')
>     ^^^^^^^^^^^^^^
> AttributeError: 'Engine' object has no attribute 'execute'
> 
> K:\cnpj>

Esse é o comando que eu dou. São os arquivos novos de 2023. Testei em outro computador e deu o mesmo erro. Nesse outro computador eu nunca tinha instalado o pyhon. Os arquivos extraídos aparecerem na pasta correta, eu mudei o comando, igual no post que comentou, mas continuou a mesma coisa.

**Comment by rictom** [comment]
Essa está difícil... 
Copia aqui as linhas 
pasta_compactados = r"dados-publicos-zip" #local dos arquivos zipados da Receita
pasta_saida = r"dados-publicos" #esta pasta deve estar vazia. 
do seu script para eu ver.

**Comment by rictom** [comment]
Vc executou em um console do dos?
Foi 
K:\cnpj>python dados_cnpj_para_sqlite.py
??
Como vc instalou o python (anaconda ou python puro?)
Se vc usou anaconda, o correto seria algo como 
(base) K:\cnpj>python dados_cnpj_para_sqlite.py
porque vc tem que abrir o console no "ambiente correto", via "anaconda prompt"

**Comment by Eduardomb22** [comment]
Eu instalei o python puro mesmo, aquele que baixamos do site. Eu rodei pelo console, entrei na pasta K:\cnpj e rodei o script, ele descompactou os arquivos, mas assim que carrega a tabela, ele dá o erro.
Eu vou tentar resolver a questão sozinho, pois achei que pudesse ser algum problema no script, mas pelo jeito é algo que eu estou fazendo.

**Comment by fastrick** [comment]
Isso é por que o sqlalchemy foi atualizado para a versão 2.0. Para usar esse código você precisa instalar a versão 1.4. Faz o seguinte:
`pip uninstall  sqlalchemy`
'pip install sqlalchemy==1.4'
Isso deve resover o problema. Abraço

**Comment by Eduardomb22** [comment]
Obrigado, problema resolvido!!!

**Comment by Eduardomb22** [comment]
> fim parcial... Mon Feb 13 06:40:02 2023
> fim sqls... Mon Feb 13 06:40:02 2023
> Aplicando VACUUM para diminuir o tamanho da base-------------------------------- Mon Feb 13 06:40:03 2023
> Traceback (most recent call last):
>   File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
>     self.dialect.do_execute(
>   File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
>     cursor.execute(statement, parameters)
> sqlite3.OperationalError: database or disk is full
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "K:\teste-cnpj\dados_cnpj_para_sqlite.py", line 206, in <module>
>     engine.execute('VACUUM')
>   File "<string>", line 2, in execute
>   File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\deprecations.py", line 390, in warned
>     return fn(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 3108, in execute
>     return connection.execute(statement, *multiparams, **params)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1247, in execute
>     return self._exec_driver_sql(
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1546, in _exec_driver_sql
>     ret = self._execute_context(
>           ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1813, in _execute_context
>     self._handle_dbapi_exception(
>   File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1994, in _handle_dbapi_exception
>     util.raise_(
>   File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\util\compat.py", line 207, in raise_
>     raise exception
>   File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\base.py", line 1770, in _execute_context
>     self.dialect.do_execute(
>   File "C:\Users\Eduardo\AppData\Local\Programs\Python\Python311\Lib\site-packages\sqlalchemy\engine\default.py", line 717, in do_execute
>     cursor.execute(statement, parameters)
> sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database or disk is full
> [SQL: VACUUM]
> (Background on this error at: http://sqlalche.me/e/14/e3q8)
> 
> K:\teste-cnpj>py dados_cnpj_para_sqlite.py

Deixei o programa rodando de madrugada e deu este erro.
Aparentemente, todos os dados estão lá, posso assumir isso?
O disco não está cheio.

**Comment by rictom** [comment]
Sim, se o arquivo foi gerado, já dá pra trabalhar com a base. Só cheque se a tabela estabelecimento tem mais de 55 milhões de registros.

O comando vacuum é um recurso adicional que serve diminuir o tamanho do arquivo cnpj.db, removendo as tabelas temporárias. Creio que diminui um pouco o tamanho do arquivo final de uns 35GB para 27GB... Talvez o seu disco K não tenha 27GB adicionais para fazer essa concluir o vacuum? Se não for isso, vc pode tentar a função "optimize table" do DB Browser for sqlite.

**Comment by Eduardomb22** [comment]
Perfeito, muito obrigado a todos!!
