### ISSUE TITLE
DROP COLUMN etapa 3/21

### ISSUE THREAD

**Issue by fastrick** [rictom/cnpj-sqlite#14]
- Arquivo executado: **dados_cnpj_para_sqlite.py**

Durante alguns testes, notei um problema na etapa 3. O erro é em relação a uma parte da variável sql, especificamente na query **ALTER TABLE empresas DROP COLUMN capital_social_str;**. Fiz o debug do código e removendo essa linha tudo ocorre perfeitamente. Pelo que pude compreender, a remoção dessa linha não interfere no resultado final já que provavelmente esta coluna não será utilizada posteriormente. Talvez o único ônus, ao meu entender, é na performance e no espaço ocupado. Percebi também que essa linha foi adicionada na última alteração desse arquivo, então pode não ter sido testada. 
Durante a etapa do debug rodei a seguinte query: **PRAGMA table_info(empresas);** No output desta query consta a coluna **capital_social_str**. Ou seja, o erro não é pela inexistência da coluna.

Não cheguei a tentar corrigir o problema. Caso encontre alguma solução atualizo aqui.

** OS: debian 11

**Comment by rictom** [comment]
Deve ter alguma versão do sqlite, que nas versões antigas o comando DROP COLUMN não funcionava. Acho que se atualizar o sqlite3 deve funcionar. Obs: Pra funcionar tem que usar um sqlalchemy anterior a 2.0, que senão dá uma incompatibilidade com o Pandas.

**Comment by fastrick** [comment]
Quanto ao sql alchemy esta tudo certo. Vou conferir a versao do SQLite. Obrigado pelo feedback
