### ISSUE TITLE
Criação do CNPJ.db

### ISSUE THREAD

**Issue by LESNeto** [rictom/cnpj-sqlite#16]
Bom Dia,
Primeiramente, 
Gostaria de lhe parabenizar pelo projeto. 
Em seguida lhe informo que não estou conseguindo finalizar a instalação local.
Tutorial para o Test tudo certo. 
Agora, para usar a Base Completa, travou.
Segui o passo a passo, baixando todos os arquivos, criando pastas, instalando bibliotecas pelo pip txt, mas quando coloco para rodar o python dados_cnpj_para_sqlite.py
 
Aparece a seguinte mensagem de erro:
 
![image](https://github.com/rictom/cnpj-sqlite/assets/133971082/7181ccc8-f626-4c8f-a93d-2b21186cb748)

(...) line 72 <title>cnpj-sqlite/dados_cnpj_lista_url.py at main · rictom/cnpj-sqlite · GitHub</title>

SyntaxError: invalid character '·' (U+00B7)
 
Como resolver?
Lhe agradeço imensamente,

**Comment by rictom** [comment]
Olá @LESNeto 

Primeiramente, vc clonou o projeto cnpj-sqlite?
Outra coisa, vc tem que ir a página de dados abertos da Receita e baixar os arquivos zipados csv.

**Comment by LESNeto** [comment]
Sim. Tudo certo.
esta tudo aí
![image](https://github.com/rictom/cnpj-sqlite/assets/133971082/e6ebb218-0667-4a24-89cb-0efb40d4c537)

**Comment by rictom** [comment]
vc baixou os arquivos?

**Comment by LESNeto** [comment]
Sim, todos, na pasta indicada.
![image](https://github.com/rictom/cnpj-sqlite/assets/133971082/c697ed87-7957-4536-bee8-a4efc26378bf)

**Comment by rictom** [comment]
Tem uma coisa, vc instalou o Anaconda? Se for executar comando no console, precisa abrir o console no ambiente do Anaconda...
![image](https://github.com/rictom/cnpj-sqlite/assets/71139693/fb9b944b-c7f3-4da2-81af-d9f37aa3eafa)
No console, daí ficaria algo começando com (base)

**Comment by rictom** [comment]
Vc tem que estar no diretório do script dados_cnpj_para_sqlite.py. Se vc der um dir *.*, vc lista e vê se está aí

**Comment by LESNeto** [comment]
![image](https://github.com/rictom/cnpj-sqlite/assets/133971082/37a96ff2-316e-4f07-8d6f-a2b04f73392d)
acho que agora vai

**Comment by LESNeto** [comment]
Quase deu.
![image](https://github.com/rictom/cnpj-sqlite/assets/133971082/67ae4c52-b095-4572-a502-5b497d0835c3)

**Comment by rictom** [comment]
Esse arquivo tá na pasta? o com o CNAE?

**Comment by LESNeto** [comment]
Vi agora que faltou este... me desculpe...
Parece que ta rodando agora... aviso na sequencia!!!

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows

De: ***@***.***>
Enviado:quinta-feira, 18 de maio de 2023 09:29
Para: ***@***.***>
***@***.***>; ***@***.***>
Assunto: Re: [rictom/cnpj-sqlite] Criação do CNPJ.db (Issue #16)


Esse arquivo tá na pasta? o com o CNAE?
