### ISSUE TITLE
AttributeError: 'Engine' object has no attribute 'execute'

### ISSUE THREAD

**Issue by LucasLaporti** [rictom/cnpj-sqlite#17]
Bom dia!
Alguém poderia me ajudar sobre o seguinte erro que me deparei ao rodar o script, por favor?

![image](https://github.com/rictom/cnpj-sqlite/assets/127100034/98be3309-fc98-4103-8a4b-21605210ff02)

**Comment by rictom** [comment]
Oi @LucasLaporti 

Tinha uma incompatibilidade entre o pandas e o sqlalchemy. 
Resolvia pegando uma versão anterior do sqlalchemy, pelo comando
pip install sqlalchemy==1.4.47

**Comment by tardoproto** [comment]
> Oi @LucasLaporti
> 
> Tinha uma incompatibilidade entre o pandas e o sqlalchemy. Resolvia pegando uma versão anterior do sqlalchemy, pelo comando pip install sqlalchemy==1.4.47

Confirmo que isso resolveu o mesmo erro para mim. Aproveito para agradecer e parabenizar pelo trabalho. Abs!
