### ISSUE TITLE
Erro executando parte 5/21

### ISSUE THREAD

**Issue by henriquearake1** [rictom/cnpj-sqlite#18]
Olá, estou rodando o script. Todos os arquivos foram baixados. Deixei o script rodando a madrugada e ocorreu o seguinte erro:

"sqlite3.OperationalError: database or disk is full"

Segue a íntegra:

C:\Users\arake\OneDrive\Documentos\rede-cnpj-master\cnpj-sqlite-main\dados_cnpj_para_sqlite.py:48: RemovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  engine.execute(f'CREATE INDEX idx_{nomeTabela} ON {nomeTabela}(codigo);')
carregando tabela dados-publicos\F.K03200$Z.D30513.MOTICSV
carregando tabela dados-publicos\F.K03200$Z.D30513.MUNICCSV
carregando tabela dados-publicos\F.K03200$Z.D30513.NATJUCSV
carregando tabela dados-publicos\F.K03200$Z.D30513.PAISCSV
carregando tabela dados-publicos\F.K03200$Z.D30513.QUALSCSV
carregando: arq='dados-publicos\\K3241.K03200Y0.D30513.EMPRECSV'
lendo csv ... Sat May 20 19:36:37 2023
fim parcial... Sat May 20 19:39:28 2023
carregando: arq='dados-publicos\\K3241.K03200Y1.D30513.EMPRECSV'
lendo csv ... Sat May 20 19:39:28 2023
fim parcial... Sat May 20 19:40:15 2023
carregando: arq='dados-publicos\\K3241.K03200Y2.D30513.EMPRECSV'
lendo csv ... Sat May 20 19:40:15 2023
fim parcial... Sat May 20 19:40:59 2023
carregando: arq='dados-publicos\\K3241.K03200Y3.D30513.EMPRECSV'
lendo csv ... Sat May 20 19:40:59 2023
fim parcial... Sat May 20 19:41:47 2023
carregando: arq='dados-publicos\\K3241.K03200Y4.D30513.EMPRECSV'
lendo csv ... Sat May 20 19:41:47 2023
fim parcial... Sat May 20 19:42:39 2023
carregando: arq='dados-publicos\\K3241.K03200Y5.D30513.EMPRECSV'
lendo csv ... Sat May 20 19:42:39 2023
fim parcial... Sat May 20 19:43:27 2023
carregando: arq='dados-publicos\\K3241.K03200Y6.D30513.EMPRECSV'
lendo csv ... Sat May 20 19:43:27 2023
fim parcial... Sat May 20 19:44:12 2023
carregando: arq='dados-publicos\\K3241.K03200Y7.D30513.EMPRECSV'
lendo csv ... Sat May 20 19:44:12 2023
fim parcial... Sat May 20 19:44:58 2023
carregando: arq='dados-publicos\\K3241.K03200Y8.D30513.EMPRECSV'
lendo csv ... Sat May 20 19:44:58 2023
fim parcial... Sat May 20 19:45:49 2023
carregando: arq='dados-publicos\\K3241.K03200Y9.D30513.EMPRECSV'
lendo csv ... Sat May 20 19:45:49 2023
fim parcial... Sat May 20 19:46:39 2023
carregando: arq='dados-publicos\\K3241.K03200Y0.D30513.ESTABELE'
lendo csv ... Sat May 20 19:46:39 2023
fim parcial... Sat May 20 19:58:11 2023
carregando: arq='dados-publicos\\K3241.K03200Y1.D30513.ESTABELE'
lendo csv ... Sat May 20 19:58:11 2023
fim parcial... Sat May 20 20:01:34 2023
carregando: arq='dados-publicos\\K3241.K03200Y2.D30513.ESTABELE'
lendo csv ... Sat May 20 20:01:34 2023
fim parcial... Sat May 20 20:04:57 2023
carregando: arq='dados-publicos\\K3241.K03200Y3.D30513.ESTABELE'
lendo csv ... Sat May 20 20:04:57 2023
fim parcial... Sat May 20 20:09:31 2023
carregando: arq='dados-publicos\\K3241.K03200Y4.D30513.ESTABELE'
lendo csv ... Sat May 20 20:09:31 2023
fim parcial... Sat May 20 20:12:40 2023
carregando: arq='dados-publicos\\K3241.K03200Y5.D30513.ESTABELE'
lendo csv ... Sat May 20 20:12:40 2023
fim parcial... Sat May 20 20:15:50 2023
carregando: arq='dados-publicos\\K3241.K03200Y6.D30513.ESTABELE'
lendo csv ... Sat May 20 20:15:50 2023
fim parcial... Sat May 20 20:19:00 2023
carregando: arq='dados-publicos\\K3241.K03200Y7.D30513.ESTABELE'
lendo csv ... Sat May 20 20:19:00 2023
fim parcial... Sat May 20 20:22:10 2023
carregando: arq='dados-publicos\\K3241.K03200Y8.D30513.ESTABELE'
lendo csv ... Sat May 20 20:22:10 2023
fim parcial... Sat May 20 20:25:24 2023
carregando: arq='dados-publicos\\K3241.K03200Y9.D30513.ESTABELE'
lendo csv ... Sat May 20 20:25:24 2023
fim parcial... Sat May 20 20:31:44 2023
carregando: arq='dados-publicos\\K3241.K03200Y0.D30513.SOCIOCSV'
lendo csv ... Sat May 20 20:31:44 2023
fim parcial... Sat May 20 20:33:24 2023
carregando: arq='dados-publicos\\K3241.K03200Y1.D30513.SOCIOCSV'
lendo csv ... Sat May 20 20:33:24 2023
fim parcial... Sat May 20 20:34:00 2023
carregando: arq='dados-publicos\\K3241.K03200Y2.D30513.SOCIOCSV'
lendo csv ... Sat May 20 20:34:00 2023
fim parcial... Sat May 20 20:34:33 2023
carregando: arq='dados-publicos\\K3241.K03200Y3.D30513.SOCIOCSV'
lendo csv ... Sat May 20 20:34:33 2023
fim parcial... Sat May 20 20:35:06 2023
carregando: arq='dados-publicos\\K3241.K03200Y4.D30513.SOCIOCSV'
lendo csv ... Sat May 20 20:35:06 2023
fim parcial... Sat May 20 20:35:42 2023
carregando: arq='dados-publicos\\K3241.K03200Y5.D30513.SOCIOCSV'
lendo csv ... Sat May 20 20:35:42 2023
fim parcial... Sat May 20 20:36:17 2023
carregando: arq='dados-publicos\\K3241.K03200Y6.D30513.SOCIOCSV'
lendo csv ... Sat May 20 20:36:17 2023
fim parcial... Sat May 20 20:36:55 2023
carregando: arq='dados-publicos\\K3241.K03200Y7.D30513.SOCIOCSV'
lendo csv ... Sat May 20 20:36:55 2023
fim parcial... Sat May 20 21:37:25 2023
carregando: arq='dados-publicos\\K3241.K03200Y8.D30513.SOCIOCSV'
lendo csv ... Sat May 20 21:37:25 2023
fim parcial... Sat May 20 21:38:10 2023
carregando: arq='dados-publicos\\K3241.K03200Y9.D30513.SOCIOCSV'
lendo csv ... Sat May 20 21:38:10 2023
fim parcial... Sat May 20 21:38:44 2023
carregando: arq='dados-publicos\\F.K03200$W.SIMPLES.CSV.D30513'
lendo csv ... Sat May 20 21:38:44 2023
fim parcial... Sat May 20 21:45:25 2023
Inicio sqls: Sat May 20 21:45:25 2023
--------------------
executando parte 1/21:

ALTER TABLE empresas ADD COLUMN capital_social real
fim parcial... Sat May 20 21:45:25 2023
--------------------
executando parte 2/21:

update  empresas
set capital_social = cast( replace(capital_social_str,',', '.') as real)
fim parcial... Sun May 21 03:56:27 2023
--------------------
executando parte 3/21:

ALTER TABLE empresas DROP COLUMN capital_social_str
fim parcial... Sun May 21 04:00:00 2023
--------------------
executando parte 4/21:

ALTER TABLE estabelecimento ADD COLUMN cnpj text
fim parcial... Sun May 21 04:00:00 2023
--------------------
executando parte 5/21:

Update estabelecimento
set cnpj = cnpj_basico||cnpj_ordem||cnpj_dv
Traceback (most recent call last):
  File "C:\Users\arake\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\arake\anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database or disk is full

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\arake\OneDrive\Documentos\rede-cnpj-master\cnpj-sqlite-main\dados_cnpj_para_sqlite.py", line 194, in <module>
    engine.execute(sql)
  File "<string>", line 2, in execute
  File "C:\Users\arake\anaconda3\lib\site-packages\sqlalchemy\util\deprecations.py", line 468, in warned
    return fn(*args, **kwargs)
  File "C:\Users\arake\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 3257, in execute
    return connection.execute(statement, *multiparams, **params)
  File "C:\Users\arake\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1365, in execute
    return self._exec_driver_sql(
  File "C:\Users\arake\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1669, in _exec_driver_sql
    ret = self._execute_context(
  File "C:\Users\arake\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "C:\Users\arake\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "C:\Users\arake\anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 211, in raise_
    raise exception
  File "C:\Users\arake\anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "C:\Users\arake\anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database or disk is full
[SQL:
Update estabelecimento
set cnpj = cnpj_basico||cnpj_ordem||cnpj_dv]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by rictom** [comment]
Como apareceu um "database or disk is full", provavelmente o seu HD não tinha espaço suficiente para a operação.  Essa tabela vai ocupar uns 28GB. Veja se vc tem esse espaço no disco.

**Comment by henriquearake1** [comment]
Resolvido! Foi exatamente isso. Eu achei estranho porque eu ainda tinha 20 gigas livres, mas parecee que foi isso mesmo. Muito obrigado!
