### ISSUE TITLE
Busca a partir de nome fantasia

### ISSUE THREAD

**Issue by OlavoPNeto** [rictom/cnpj-sqlite#2]
É possivel buscar por dados como cnpj, telefone e endereço a partir do nome fantasia do estabelecimento ?
Trabalho na área de prospecção de uma empresa em busca de potenciais clientes, e estou tentar por em prática meus estudos em python!

**Comment by rictom** [comment]
A coluna nome_fantasia está na tabela estabelecimento. Para fazer a busca, para não ficar lento, vc deve criar primeiro um índice na coluna. 
Vc abre o arquivo sqlite no DB Browser for Sqlite, e roda o comando SQL
CREATE INDEX "idx_nome_fantasia" ON "estabelecimento" ("nome_fantasia")
Depois do índice ser criado, vc faz uma consulta pela coluna fazendo
Select *
from estabelecimento
where nome_fantasia="nome da empresa"

Se quiser fazer consulta pela parte final do nome fantasia:
Select *
from estabelecimento
where nome_fantasia like "comeco do nome%"

O percentual % serve como caractere curinga.
Fazer consulta com o operador like "%nome%" deve ficar lento, daí vc tem que ver como usar a função MATCH do sqlite (mas daí precisa criar outro tipo de índice (https://www.sqlitetutorial.net/sqlite-full-text-search/)
