### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by TheEconomistBR** [rictom/cnpj-sqlite#20]
![image](https://github.com/rictom/cnpj-sqlite/assets/86390913/cea3b321-b3cb-4a94-a60a-a10c2333e039)
o que fiz de errado para está assim?

**Comment by rictom** [comment]
Se vc instalou o Anaconda, tem que ativar o prompt pelo atalho no Anaconda, para o Python estar no ambiente correto. 
Vc instalou o Anaconda? 
Na página https://github.com/rictom/cnpj-sqlite tem a explicação de como acessar o prompt do Anaconda. Siga o passo a passo.
Daí todas as linhas do prompt começam com (base) C:...
Primeira coisa a fazer é rodar o comando pip install -r requirements.txt. 
Outra coisa é que vc está usando o Powershell, que tem umas diferenças com o cmd do DOS. Como não uso o PowerShell, não sei se funciona nele.

**Comment by rictom** [comment]
Pelo que estou vendo, acho que vc não baixou os arquivos zip do site da receita. São 37 arquivos que devem estar na pasta dados-publicos-zip. Vc tem que baixar manualmente de https://dadosabertos.rfb.gov.br/CNPJ/ ou rodar o script 
python dados_cnpj_baixa.py

**Comment by TheEconomistBR** [comment]
[image: image.png]
Agora deu esse erro, sabe o motivo?

Em dom., 2 de jul. de 2023 às 19:15, rictom ***@***.***>
escreveu:

**Comment by rictom** [comment]
Não dá pra ver nenhuma imagem.

**Comment by TheEconomistBR** [comment]
deu um erro e coloquei outra versão do sql.
Depois de corrigido não deu mais erro.
porem quando coloco o arquivo que foi gerado so aparece ocnae com a base em
si, empresa, socio não tem nada..Sabe me dizer onde estou errando?
Mandei os print. Obrigado pela atenção

Em dom., 2 de jul. de 2023 às 21:15, rictom ***@***.***>
escreveu:

**Comment by rictom** [comment]
A pasta dados-publicos-zip tem que ter 37 arquivos. Dá um print dessa pasta pra saber quais arquivos estão lá.

**Comment by TheEconomistBR** [comment]
Em dom., 2 de jul. de 2023 às 21:54, rictom ***@***.***>
escreveu:

**Comment by TheEconomistBR** [comment]
Consegueria me dizer onde estou errando? agradeço demais a ajuda!

Em dom., 2 de jul. de 2023 às 22:04, Lucas Tanaro ***@***.***>
escreveu:

**Comment by rictom** [comment]
Eu não estou conseguindo entender, primeiro que não consegui ver a imagem e não sei se vc seguiu o passo a passo. Por exemplo, você tem 37 arquivos na dados-publicos-zip? Se eu não tiver idéia de qual comando você deu, qual a mensagem de erro apareceu, um print de tela, fica impossível fazer algum diagnóstico. 
Se você nunca mexeu com python, sugiro você ir lá em https://www.redecnpj.com.br/rede/aviso e baixar o "Programa para baixar os Dados Abertos e usar na RedeCNPJ Aplicativo" e roda a parte 01 e 02 para gerar um arquivo cnpj.db com a base de empresas. Esses são versões exe do código que está neste github.

**Comment by TheEconomistBR** [comment]
vou fazer o que você disse.. olha o que dei novamente.

Em dom., 2 de jul. de 2023 às 22:39, rictom ***@***.***>
escreveu:

**Comment by TheEconomistBR** [comment]
Boa tarde! Conseguir baixar e visualizar os dados. Agora ele está no
processo 3, conforme a imagem, está executando 3/4 desde 14h do dia de
hoje, sabe me dizer se demora assim mesmo?
Minha outra dúvida é referente a localização, eu consigo filtrar para saber
somente a relação de socios em determinado Estado?

Em seg., 3 de jul. de 2023 às 00:29, Lucas Tanaro ***@***.***>
escreveu:

**Comment by rictom** [comment]
Sim, depende do seu computador. O tempo estimado é de umas duas horas, mas se o seu computador não tiver SSD provavelmente vai levar mais tempo.
As partes 3 e 4 são só necessárias se você for usar a redecnpj aplicativo... Se o seu objetivo é ter a base de cnpjs, vc deve ter conseguido gerar a tabela cnpj.db. Se tudo estiver correto deve ter uns 30GB. 
Aqui no projeto tem uma pasta exemplos de consultas SQL para filtrar empresas por natureza jurídica. Vc conseguiria filtrar empresas por município e UF, por exemplo.

**Comment by TheEconomistBR** [comment]
Tem sdd sim, vou aguardar. Não localizei essa pasta exemplos, está onde
baixei o arquivo zip?

Em seg., 3 de jul. de 2023 às 17:10, rictom ***@***.***>
escreveu:

**Comment by TheEconomistBR** [comment]
Acheii, seria esse codigo para eu achar de determinado estado?
 SELECT t.*, te.*, ts.*
FROM empresas te
LEFT JOIN estabelecimento t ON t.cnpj_basico = te.cnpj_basico
LEFT JOIN socios ts ON ts.cnpj = t.cnpj
WHERE (te.natureza_juridica = "2143" OR te.natureza_juridica = "2330")
AND t.uf = "MS"



Em seg., 3 de jul. de 2023 às 17:15, Lucas Tanaro ***@***.***>
escreveu:

**Comment by TheEconomistBR** [comment]
Boa noite amigo, desculpa ser chato.
consegueria me responder se essa função seria a correta para achar sobre o
estado de MS?

Em seg., 3 de jul. de 2023 às 17:56, Lucas Tanaro ***@***.***>
escreveu:

**Comment by rictom** [comment]
Olha, aparentemente é isso mesmo. É mais fácil testar do que tentar saber se está correto... A dica que posso dar é por um limit no final, sei lá, limit 100 só pra pegar os 100 primeiros registros, daí vc vê se os resultados estão consistentes, daí tira o limit.

**Comment by WagnerDorneles** [comment]
> Se vc instalou o Anaconda, tem que ativar o prompt pelo atalho no Anaconda, para o Python estar no ambiente correto. Vc instalou o Anaconda? Na página https://github.com/rictom/cnpj-sqlite tem a explicação de como acessar o prompt do Anaconda. Siga o passo a passo. Daí todas as linhas do prompt começam com (base) C:... Primeira coisa a fazer é rodar o comando pip install -r requirements.txt. Outra coisa é que vc está usando o Powershell, que tem umas diferenças com o cmd do DOS. Como não uso o PowerShell, não sei se funciona nele.

Pergunta posso rodar dentro do VSCODE ou tem que rodar pelo prompt da anaconda.
