### ISSUE TITLE
Não é erro é uma curiosidade

### ISSUE THREAD

**Issue by tiagoftavares** [rictom/cnpj-sqlite#21]
Esse caminho:  'http://200.152.38.155/CNPJ/' é um caminho público ou é alimentado de alguma outra forma? Esses arquivos são atualizados?

Muito obrigado amigo, seu script tem me ajudado muito.

**Comment by rictom** [comment]
Esse é um servidor da Receita Federal, acho que desde 2020 era neste local que ela publica os dados. 

Se vc for lá no portal de dados abertos, https://dados.gov.br/dados/conjuntos-dados/cadastro-nacional-da-pessoa-juridica---cnpj, e clicar para baixar algum dos arquivos, dá para ver que o endereço é  https://dadosabertos.rfb.gov.br/CNPJ/  (essa página tem a mesma cara de http://200.152.38.155/CNPJ/).
Realmente, pro script talvez fosse melhor pegar as tabelas de https://dadosabertos.rfb.gov.br/CNPJ/, mas como até agora estava funcionando, não alterei.
