### ISSUE TITLE
SQLALCHEMY 2.0

### ISSUE THREAD

**Issue by WagnerDorneles** [rictom/cnpj-sqlite#25]
Olá tudo bem 👍 

Estou aprendendo a programação e olhando seu projeto sobre o sqlalchemy que está na versão 2.0 , não deu erro, mas apareceu esse aviso para silenciar as mensagens.

![image](https://github.com/rictom/cnpj-sqlite/assets/150027068/7b94d110-7670-4c24-87a0-d666ccb7b712)

Algo que possamos fazer para solução ou somente  comentar no código mesmo e silenciar os avisos.

Parabéns pelo projeto.

**Comment by rictom** [comment]
Eu substitui a parte do código que dependia da conexão em sqlalchemy. Para usar sqlalchemy 2.x, teria que colocar onde tinha engine.execute(sql) algo como engine.execute(sqlalchemy.text(sql))... Assim, usando a engine do sqlite3, dá para manter o código sem alterar.
