### ISSUE TITLE
sqlite3.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by simoyama2** [rictom/cnpj-sqlite#26]
Olá

Tentei executar o script 3 vezes, nas 3 ocorreu esse erro abaixo. Já tentei excluir e baixar novamente os arquivos ZIP, mas não deu certo (mesmo erro).

Início: Tue Jan 23 11:30:36 2024
Tue Jan 23 11:30:36 2024 descompactando dados-publicos-zip\Cnaes.zip
Tue Jan 23 11:30:36 2024 descompactando dados-publicos-zip\Empresas0.zip
Tue Jan 23 11:30:54 2024 descompactando dados-publicos-zip\Empresas1.zip
Tue Jan 23 11:30:59 2024 descompactando dados-publicos-zip\Empresas2.zip
Tue Jan 23 11:31:05 2024 descompactando dados-publicos-zip\Empresas3.zip
Tue Jan 23 11:31:10 2024 descompactando dados-publicos-zip\Empresas4.zip
Tue Jan 23 11:31:15 2024 descompactando dados-publicos-zip\Empresas5.zip
Tue Jan 23 11:31:20 2024 descompactando dados-publicos-zip\Empresas6.zip
Tue Jan 23 11:31:26 2024 descompactando dados-publicos-zip\Empresas7.zip
Tue Jan 23 11:31:31 2024 descompactando dados-publicos-zip\Empresas8.zip
Tue Jan 23 11:31:36 2024 descompactando dados-publicos-zip\Empresas9.zip
Tue Jan 23 11:31:42 2024 descompactando dados-publicos-zip\Estabelecimentos0.zip
Tue Jan 23 11:32:44 2024 descompactando dados-publicos-zip\Estabelecimentos1.zip
Tue Jan 23 11:33:02 2024 descompactando dados-publicos-zip\Estabelecimentos2.zip
Tue Jan 23 11:33:21 2024 descompactando dados-publicos-zip\Estabelecimentos3.zip
Tue Jan 23 11:33:40 2024 descompactando dados-publicos-zip\Estabelecimentos4.zip
Tue Jan 23 11:34:00 2024 descompactando dados-publicos-zip\Estabelecimentos5.zip
Tue Jan 23 11:34:20 2024 descompactando dados-publicos-zip\Estabelecimentos6.zip
Tue Jan 23 11:34:38 2024 descompactando dados-publicos-zip\Estabelecimentos7.zip
Tue Jan 23 11:34:57 2024 descompactando dados-publicos-zip\Estabelecimentos8.zip
Tue Jan 23 11:35:16 2024 descompactando dados-publicos-zip\Estabelecimentos9.zip
Tue Jan 23 11:35:35 2024 descompactando dados-publicos-zip\Motivos.zip
Tue Jan 23 11:35:35 2024 descompactando dados-publicos-zip\Municipios.zip
Tue Jan 23 11:35:35 2024 descompactando dados-publicos-zip\Naturezas.zip
Tue Jan 23 11:35:35 2024 descompactando dados-publicos-zip\Paises.zip
Tue Jan 23 11:35:35 2024 descompactando dados-publicos-zip\Qualificacoes.zip
Tue Jan 23 11:35:35 2024 descompactando dados-publicos-zip\Simples.zip
Tue Jan 23 11:36:02 2024 descompactando dados-publicos-zip\Socios0.zip
Tue Jan 23 11:36:11 2024 descompactando dados-publicos-zip\Socios1.zip
Tue Jan 23 11:36:14 2024 descompactando dados-publicos-zip\Socios2.zip
Tue Jan 23 11:36:18 2024 descompactando dados-publicos-zip\Socios3.zip
Tue Jan 23 11:36:21 2024 descompactando dados-publicos-zip\Socios4.zip
Tue Jan 23 11:36:24 2024 descompactando dados-publicos-zip\Socios5.zip
Tue Jan 23 11:36:27 2024 descompactando dados-publicos-zip\Socios6.zip
Tue Jan 23 11:36:31 2024 descompactando dados-publicos-zip\Socios7.zip
Tue Jan 23 11:36:34 2024 descompactando dados-publicos-zip\Socios8.zip
Tue Jan 23 11:36:37 2024 descompactando dados-publicos-zip\Socios9.zip
carregando tabela dados-publicos\F.K03200$Z.D40113.CNAECSV
carregando tabela dados-publicos\F.K03200$Z.D40113.MOTICSV
carregando tabela dados-publicos\F.K03200$Z.D40113.MUNICCSV
carregando tabela dados-publicos\F.K03200$Z.D40113.NATJUCSV
carregando tabela dados-publicos\F.K03200$Z.D40113.PAISCSV
carregando tabela dados-publicos\F.K03200$Z.D40113.QUALSCSV
carregando: arq='dados-publicos\\K3241.K03200Y0.D40113.EMPRECSV'
lendo csv ... Tue Jan 23 11:36:44 2024
fim parcial... Tue Jan 23 11:38:42 2024
carregando: arq='dados-publicos\\K3241.K03200Y1.D40113.EMPRECSV'
lendo csv ... Tue Jan 23 11:38:42 2024
fim parcial... Tue Jan 23 11:39:15 2024
carregando: arq='dados-publicos\\K3241.K03200Y2.D40113.EMPRECSV'
lendo csv ... Tue Jan 23 11:39:15 2024
fim parcial... Tue Jan 23 11:39:46 2024
carregando: arq='dados-publicos\\K3241.K03200Y3.D40113.EMPRECSV'
lendo csv ... Tue Jan 23 11:39:46 2024
fim parcial... Tue Jan 23 11:40:20 2024
carregando: arq='dados-publicos\\K3241.K03200Y4.D40113.EMPRECSV'
lendo csv ... Tue Jan 23 11:40:20 2024
fim parcial... Tue Jan 23 11:40:56 2024
carregando: arq='dados-publicos\\K3241.K03200Y5.D40113.EMPRECSV'
lendo csv ... Tue Jan 23 11:40:56 2024
fim parcial... Tue Jan 23 11:41:32 2024
carregando: arq='dados-publicos\\K3241.K03200Y6.D40113.EMPRECSV'
lendo csv ... Tue Jan 23 11:41:32 2024
fim parcial... Tue Jan 23 11:42:06 2024
carregando: arq='dados-publicos\\K3241.K03200Y7.D40113.EMPRECSV'
lendo csv ... Tue Jan 23 11:42:06 2024
fim parcial... Tue Jan 23 11:42:44 2024
carregando: arq='dados-publicos\\K3241.K03200Y8.D40113.EMPRECSV'
lendo csv ... Tue Jan 23 11:42:44 2024
fim parcial... Tue Jan 23 11:43:23 2024
carregando: arq='dados-publicos\\K3241.K03200Y9.D40113.EMPRECSV'
lendo csv ... Tue Jan 23 11:43:23 2024
fim parcial... Tue Jan 23 11:44:00 2024
carregando: arq='dados-publicos\\K3241.K03200Y0.D40113.ESTABELE'
lendo csv ... Tue Jan 23 11:44:00 2024
fim parcial... Tue Jan 23 11:51:44 2024
carregando: arq='dados-publicos\\K3241.K03200Y1.D40113.ESTABELE'
lendo csv ... Tue Jan 23 11:51:44 2024
fim parcial... Tue Jan 23 11:54:02 2024
carregando: arq='dados-publicos\\K3241.K03200Y2.D40113.ESTABELE'
lendo csv ... Tue Jan 23 11:54:02 2024
fim parcial... Tue Jan 23 11:56:03 2024
carregando: arq='dados-publicos\\K3241.K03200Y3.D40113.ESTABELE'
lendo csv ... Tue Jan 23 11:56:03 2024
fim parcial... Tue Jan 23 11:58:03 2024
carregando: arq='dados-publicos\\K3241.K03200Y4.D40113.ESTABELE'
lendo csv ... Tue Jan 23 11:58:03 2024
fim parcial... Tue Jan 23 12:00:07 2024
carregando: arq='dados-publicos\\K3241.K03200Y5.D40113.ESTABELE'
lendo csv ... Tue Jan 23 12:00:07 2024
fim parcial... Tue Jan 23 12:02:14 2024
carregando: arq='dados-publicos\\K3241.K03200Y6.D40113.ESTABELE'
lendo csv ... Tue Jan 23 12:02:14 2024
fim parcial... Tue Jan 23 12:04:12 2024
carregando: arq='dados-publicos\\K3241.K03200Y7.D40113.ESTABELE'
lendo csv ... Tue Jan 23 12:04:12 2024
fim parcial... Tue Jan 23 12:06:08 2024
carregando: arq='dados-publicos\\K3241.K03200Y8.D40113.ESTABELE'
lendo csv ... Tue Jan 23 12:06:08 2024
fim parcial... Tue Jan 23 12:08:04 2024
carregando: arq='dados-publicos\\K3241.K03200Y9.D40113.ESTABELE'
lendo csv ... Tue Jan 23 12:08:04 2024
fim parcial... Tue Jan 23 12:10:02 2024
carregando: arq='dados-publicos\\K3241.K03200Y0.D40113.SOCIOCSV'
lendo csv ... Tue Jan 23 12:10:02 2024
fim parcial... Tue Jan 23 12:10:57 2024
carregando: arq='dados-publicos\\K3241.K03200Y1.D40113.SOCIOCSV'
lendo csv ... Tue Jan 23 12:10:57 2024
fim parcial... Tue Jan 23 12:11:19 2024
carregando: arq='dados-publicos\\K3241.K03200Y2.D40113.SOCIOCSV'
lendo csv ... Tue Jan 23 12:11:19 2024
fim parcial... Tue Jan 23 12:11:41 2024
carregando: arq='dados-publicos\\K3241.K03200Y3.D40113.SOCIOCSV'
lendo csv ... Tue Jan 23 12:11:41 2024
fim parcial... Tue Jan 23 12:12:03 2024
carregando: arq='dados-publicos\\K3241.K03200Y4.D40113.SOCIOCSV'
lendo csv ... Tue Jan 23 12:12:03 2024
fim parcial... Tue Jan 23 12:12:23 2024
carregando: arq='dados-publicos\\K3241.K03200Y5.D40113.SOCIOCSV'
lendo csv ... Tue Jan 23 12:12:23 2024
fim parcial... Tue Jan 23 12:12:44 2024
carregando: arq='dados-publicos\\K3241.K03200Y6.D40113.SOCIOCSV'
lendo csv ... Tue Jan 23 12:12:44 2024
fim parcial... Tue Jan 23 12:13:07 2024
carregando: arq='dados-publicos\\K3241.K03200Y7.D40113.SOCIOCSV'
lendo csv ... Tue Jan 23 12:13:07 2024
fim parcial... Tue Jan 23 12:13:31 2024
carregando: arq='dados-publicos\\K3241.K03200Y8.D40113.SOCIOCSV'
lendo csv ... Tue Jan 23 12:13:31 2024
fim parcial... Tue Jan 23 12:13:53 2024
carregando: arq='dados-publicos\\K3241.K03200Y9.D40113.SOCIOCSV'
lendo csv ... Tue Jan 23 12:13:53 2024
fim parcial... Tue Jan 23 12:14:13 2024
carregando: arq='dados-publicos\\F.K03200$W.SIMPLES.CSV.D40113'
lendo csv ... Tue Jan 23 12:14:13 2024
fim parcial... Tue Jan 23 12:18:15 2024
Inicio sqls: Tue Jan 23 12:18:15 2024
--------------------
executando parte 1/21:
 
ALTER TABLE empresas ADD COLUMN capital_social real
fim parcial... Tue Jan 23 12:18:15 2024
--------------------
executando parte 2/21:
 
update  empresas
set capital_social = cast( replace(capital_social_str,',', '.') as real)
Traceback (most recent call last):
  File "E:\Novo Script para criar DB de CNPJ\cnpj-sqlite-main\cnpj-sqlite-main\dados_cnpj_para_sqlite.py", line 196, in <module>
    engine.execute(sql)
sqlite3.DatabaseError: database disk image is malformed

Process finished with exit code 1

**Comment by rictom** [comment]
No windows, a biblioteca sqlite usa o disco principal para salvar os arquivos temporários, mesmo que vc use um disco externo para rodar a rotina. Você tem espaço razoável livre no disco C:? Pelo menos uns 60GB?

**Comment by simoyama2** [comment]
> No windows, a biblioteca sqlite usa o disco principal para salvar os arquivos temporários, mesmo que vc use um disco externo para rodar a rotina. Você tem espaço razoável livre no disco C:? Pelo menos uns 60GB?

Realmente esse era o problema. Agora foi resolvido e consegui gerar o banco. Obrigado
