### ISSUE TITLE
acho que o banco que eu tenho já tem os cnae secundário, isso no mysql, pois importei o banco do sqlite

### ISSUE THREAD

**Issue by rictom** [rictom/cnpj-sqlite#28]
acho que o banco que eu tenho já tem os cnae secundário, isso no mysql, pois importei o banco do sqlite

na tabela estabelecimentos tem um campo cnae_fiscal_secundaria

essa rotina do .py faz é separar em outra tabela?

_Originally posted by @fredroo in https://github.com/rictom/cnpj-sqlite/issues/27#issuecomment-1950245505_

**Comment by rictom** [comment]
A rotina pega a coluna cnae_secundaria da tabela estabelecimentos que podem ter vários cnaes separados por vírgula e cria uma nova tabela. Eu particularmente não utilizo essa coluna de forma separada, na minha aplicação eu pego e separo na hora mesmo, mas isso deve ser útil se você quiser filtrar empresas pelo cnae.
![image](https://github.com/rictom/cnpj-sqlite/assets/71139693/353d86a4-3908-4c30-9bcd-c78c528f7c82)
Por exemplo, o 8591100,4763602,4781400,4782201,4772500,9319101 vai ser quebrado em outra tabela,
CNPJXXX 8591100
CNPJXXX 4763602
etc..

**Comment by fredroo** [comment]
@rictom pior que é o que quero, preciso filtrar por cnaes, dessa forma como está agora demoraria absurdo, mas eu resolvo com php, só me diz se o correto é ficar CNPJ, CNAE

**Comment by rictom** [comment]
Sim, o resultado é uma tabela com duas colunas, CNPJ e CNAE

**Comment by fredroo** [comment]
@rictom descobri que é a paginação, eu aumentei e mudou o erro

![image](https://github.com/rictom/cnpj-sqlite/assets/6863089/1a61af91-3373-42bf-a21d-a362b6d15d8e)

**Comment by rictom** [comment]
Eu não sei se você está começando no python agora. Mas um ponto importante é trabalhar em um ambiente, onde você isola e está tudo configurado corretamente. 
Se você abre um console e digita algo como C:>python nome_script.py, vc vai estar chamando um python que está no Path do windows, mas isso pode dar problema se você tiver várias versões de python (o que é possível). 
Por isso, no descrição do projeto, eu recomendo usar o anaconda, e rodar abrir o Anaconda prompt, então tudo vai ficar mais certo. 
Se você abrir o Anaconda prompt, no console vai aparecer algo como
(base) C:\Users\<seu_usuario>
Pela tela que você colou, vc não está rodando em um ambiente. 
Se você não instalou o Anaconda, leia ao menos algum guia como o 
https://docs.python.org/3/library/venv.html
Entender como isso funciona vai evitar erros e dores de cabeça.

**Comment by fredroo** [comment]
@rictom resolvi, olha a outra issue

**Comment by fredroo** [comment]
@rictom no momento estou importando para mysql, está tudo ok, pode fechar essa issue, e se quiser muda o `chunksize=10000`
