### ISSUE TITLE
Dados antigos da receita

### ISSUE THREAD

**Issue by pedroventura12** [rictom/cnpj-sqlite#3]
Boa tarde Amigos!
Alguém que já trabalhe com dados da receita há mais tempo tem os dados de estabelecimentos que foram disponibilizados pela receita federal no inicio de 2020? 

Att, Pedro

**Comment by rictom** [comment]
O projeto https://github.com/georgevbsantiago/qsacnpj tem links para baixar arquivos de 2020 no formato sqlite e csv.
