### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by xXxjubeixXx** [rictom/cnpj-sqlite#30]
Quando executo o código:

`python dados_cnpj_para_sqlite.py`

Ele me retorna esse erro aqui:

```
Traceback (most recent call last):
  File "C:\Users\bielk\OneDrive\Documentos\Banco Receita\cnpj-sqlite-main\dados_cnpj_para_sqlite.py", line 52, in <module>
    carregaTabelaCodigo('.CNAECSV','cnae')
  File "C:\Users\bielk\OneDrive\Documentos\Banco Receita\cnpj-sqlite-main\dados_cnpj_para_sqlite.py", line 46, in carregaTabelaCodigo
    arquivo = list(glob.glob(os.path.join(pasta_saida, '*' + extensaoArquivo)))[0]
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

Quando tento executar de novo, acontece isso:

`O arquivo dados-publicos\cnpj.db já existe. Apague-o primeiro e rode este script novamente.`

**Comment by rictom** [comment]
Esse script não baixa os arquivos do site da receita. Vc precisa baixar os 37 arquivos na pasta dados-publicos-zip, que vc encontra em https://dados.gov.br/dados/conjuntos-dados/cadastro-nacional-da-pessoa-juridica---cnpj ou http://200.152.38.155/CNPJ/
Vc pode baixar os arquivos manualmente por esses links ou usa o script dados_cnpj_baixa.py.
Depois de vc ter os 37 arquivos .zip, antes de executar de novo o dados_cnpj_para_sqlite.py, vc vai ter que apagar o cnpj.db, como explica na mensagem de erro.

**Comment by xXxjubeixXx** [comment]
Consegui arrumar aqui, achei interessante postar esse erro para se alguém também passasse pelo mesmo!

**Comment by rictom** [comment]
Alterei o código para avisar se não tiver os arquivos .zip na pasta
