### ISSUE TITLE
Adicionar para SQL Server

### ISSUE THREAD

**Issue by Andre1305** [rictom/cnpj-sqlite#34]
Muito obrigado pelo projeto, está muito bem explicado e atualizado. Mas eu uso o SQL Server da Microsoft, tem como o script importar diretamente para?

Estou iniciando na área e não entendo muito.

**Comment by rictom** [comment]
Seria melhor vc dar uma olhada https://github.com/rictom/cnpj-mysql,
que a sintaxe do mysql deve ser mais parecido com o sql server. 
Como não tenho como testar em sql server não sei dizer se precisaria modificar muito o código.
Uma opção é vc gerar em sqlite mesmo, depois usar algo como o DBeaver para carregar do sqlite para o SQLServer.

**Comment by Andre1305** [comment]
Vou dar uma pesquisada, mas as bibliotecas do Python são diferentes.

Obrigado pelo retorno.
