### ISSUE TITLE
Cnpj_basico not a string

### ISSUE THREAD

**Issue by Badlands19** [rictom/cnpj-sqlite#35]
Olá, Rictom. Obrigado por disponibilizar esse projeto, já o uso há um tempo e ele é ótimo. Apenas agora que fui atualizar o banco utilizando a pasta 2024-08 do site da Receita e estou recebendo o seguinte erro ao executar "dados_cnpj_para_sqlite":

ValueError: cnpj_basico (<class 'sqlalchemy.sql.sqltypes.String'>) not a string

Tentei ajustar, mas sem sucesso. Sabe o que pode ser?

Obrigado desde já

**Comment by rictom** [comment]
Seria bom vc colar o que apareceu no console, que assim fica difícil saber.

**Comment by Badlands19** [comment]
PS C:\Users\Lenovo\Desktop\cnpj-sqlite-main_ago_24> python dados_cnpj_para_sqlite.py
Início: Thu Aug 22 11:37:32 2024
Thu Aug 22 11:37:32 2024 descompactando dados-publicos-zip\Cnaes.zip
Thu Aug 22 11:37:32 2024 descompactando dados-publicos-zip\Empresas0.zip
Thu Aug 22 11:37:38 2024 descompactando dados-publicos-zip\Empresas1.zip
Thu Aug 22 11:37:40 2024 descompactando dados-publicos-zip\Empresas2.zip
Thu Aug 22 11:37:41 2024 descompactando dados-publicos-zip\Empresas3.zip
Thu Aug 22 11:37:42 2024 descompactando dados-publicos-zip\Empresas4.zip
Thu Aug 22 11:37:44 2024 descompactando dados-publicos-zip\Empresas5.zip
Thu Aug 22 11:37:45 2024 descompactando dados-publicos-zip\Empresas6.zip
Thu Aug 22 11:37:47 2024 descompactando dados-publicos-zip\Empresas7.zip
Thu Aug 22 11:37:48 2024 descompactando dados-publicos-zip\Empresas8.zip
Thu Aug 22 11:37:50 2024 descompactando dados-publicos-zip\Empresas9.zip
Thu Aug 22 11:37:52 2024 descompactando dados-publicos-zip\Estabelecimentos0.zip
Thu Aug 22 11:38:12 2024 descompactando dados-publicos-zip\Estabelecimentos1.zip
Thu Aug 22 11:38:18 2024 descompactando dados-publicos-zip\Estabelecimentos2.zip
Thu Aug 22 11:38:22 2024 descompactando dados-publicos-zip\Estabelecimentos3.zip
Thu Aug 22 11:38:27 2024 descompactando dados-publicos-zip\Estabelecimentos4.zip
Thu Aug 22 11:38:33 2024 descompactando dados-publicos-zip\Estabelecimentos5.zip
Thu Aug 22 11:38:40 2024 descompactando dados-publicos-zip\Estabelecimentos6.zip
Thu Aug 22 11:38:47 2024 descompactando dados-publicos-zip\Estabelecimentos7.zip
Thu Aug 22 11:38:55 2024 descompactando dados-publicos-zip\Estabelecimentos8.zip
Thu Aug 22 11:39:03 2024 descompactando dados-publicos-zip\Estabelecimentos9.zip
Thu Aug 22 11:39:11 2024 descompactando dados-publicos-zip\Motivos.zip
Thu Aug 22 11:39:11 2024 descompactando dados-publicos-zip\Municipios.zip
Thu Aug 22 11:39:11 2024 descompactando dados-publicos-zip\Naturezas.zip
Thu Aug 22 11:39:11 2024 descompactando dados-publicos-zip\Paises.zip
Thu Aug 22 11:39:11 2024 descompactando dados-publicos-zip\Qualificacoes.zip
Thu Aug 22 11:39:11 2024 descompactando dados-publicos-zip\Simples.zip
Thu Aug 22 11:39:23 2024 descompactando dados-publicos-zip\Socios0.zip
Thu Aug 22 11:39:27 2024 descompactando dados-publicos-zip\Socios1.zip
Thu Aug 22 11:39:28 2024 descompactando dados-publicos-zip\Socios2.zip
Thu Aug 22 11:39:29 2024 descompactando dados-publicos-zip\Socios3.zip
Thu Aug 22 11:39:31 2024 descompactando dados-publicos-zip\Socios4.zip
Thu Aug 22 11:39:32 2024 descompactando dados-publicos-zip\Socios5.zip
Thu Aug 22 11:39:34 2024 descompactando dados-publicos-zip\Socios6.zip
Thu Aug 22 11:39:35 2024 descompactando dados-publicos-zip\Socios7.zip
Thu Aug 22 11:39:36 2024 descompactando dados-publicos-zip\Socios8.zip
Thu Aug 22 11:39:38 2024 descompactando dados-publicos-zip\Socios9.zip
carregando tabela dados-publicos\F.K03200$Z.D40810.CNAECSV
carregando tabela dados-publicos\F.K03200$Z.D40810.MOTICSV
carregando tabela dados-publicos\F.K03200$Z.D40810.MUNICCSV
carregando tabela dados-publicos\F.K03200$Z.D40810.NATJUCSV
carregando tabela dados-publicos\F.K03200$Z.D40810.PAISCSV
carregando tabela dados-publicos\F.K03200$Z.D40810.QUALSCSV
carregando: arq='dados-publicos\\K3241.K03200Y0.D40810.EMPRECSV'
lendo csv ... Thu Aug 22 11:39:39 2024
C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\dask\dataframe\io\sql.py:423: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  q = d.to_sql(con=engine, **kwargs)
Traceback (most recent call last):
  File "C:\Users\Lenovo\Desktop\cnpj-sqlite-main_ago_24\dados_cnpj_para_sqlite.py", line 156, in <module>
    carregaTipo('empresas', '.EMPRECSV', colunas_empresas)
  File "C:\Users\Lenovo\Desktop\cnpj-sqlite-main_ago_24\dados_cnpj_para_sqlite.py", line 153, in carregaTipo
    ddf.to_sql(nome_tabela, engine_url, index=None, if_exists='append', dtype=sqlalchemy.sql.sqltypes.TEXT)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\dask_expr\_collection.py", line 2424, in to_sql
    return to_sql(
           ^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\dask_expr\io\sql.py", line 356, in to_sql
    return _to_sql(
           ^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\dask\dataframe\io\sql.py", line 606, in to_sql
    dask_compute(result)
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\dask\base.py", line 662, in compute
    results = schedule(dsk, keys, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\dask\dataframe\io\sql.py", line 423, in _to_sql_chunk
    q = d.to_sql(con=engine, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\sql.py", line 842, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\io\sql.py", line 2839, in to_sql
    raise ValueError(f"{col} ({my_type}) not a string")
ValueError: cnpj_basico (<class 'sqlalchemy.sql.sqltypes.TEXT'>) not a string

**Comment by rictom** [comment]
Acho que você não está com a última versão do script dados_cnpj_para_sqlite, porque senão o erro seria na linha 152... 
Baixe essa versão mais nova, apague o cnpj.db se existir em dados-publicos...
Como você não está usando o anaconda, vc instalou o python puro? O ideal seria criar um ambiente para rodar o script, segue um roteiro como em 
https://docs.python.org/pt-br/3/library/venv.html
e nesse ambiente (apesar de ser meio chato no começo, vai te poupar dor de cabeça no futuro)
roda 
python -r requirements.txt
que carrega os pré-requisitos.

**Comment by Badlands19** [comment]
Oi, Rictom! Sua dica de instalar o virtual env deu certo! Acredito que era alguma coisa nos requerimentos mesmo, pois mesmo com o código atual tinha dado errado. Agora funcionou.
Valeu!!
